# Generated by Django 3.1.7 on 2021-09-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mail', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('user_category', models.CharField(blank=True, max_length=32, null=True)),
                ('role_type', models.CharField(blank=True, max_length=32, null=True)),
                ('login_type', models.CharField(blank=True, max_length=32, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('encoded_password', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_question', models.CharField(blank=True, max_length=255, null=True)),
                ('encoded_secret_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('encoded_custom_secret_question', models.CharField(blank=True, max_length=255, null=True)),
                ('encoded_custom_secret_answer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
