# Generated by Django 3.1.7 on 2021-10-01 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(db_column='first_name', max_length=32)),
                ('last_name', models.CharField(db_column='last_name', max_length=32)),
                ('gender', models.CharField(db_column='gender', max_length=10)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('country', models.CharField(db_column='', max_length=32)),
                ('user_category', models.CharField(blank=True, db_column='user_category', max_length=32, null=True)),
                ('role_type', models.CharField(blank=True, db_column='role_type', max_length=32, null=True)),
                ('login_type', models.CharField(blank=True, db_column='login_type', max_length=32, null=True)),
                ('username', models.CharField(blank=True, db_column='username', max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=255, null=True)),
                ('secret_question', models.CharField(blank=True, db_column='secret_question', max_length=255, null=True)),
                ('encoded_secret_answer', models.CharField(blank=True, db_column='encoded_secret_answer', max_length=255, null=True)),
                ('encoded_custom_secret_question', models.CharField(blank=True, db_column='encoded_custom_secret_question', max_length=255, null=True)),
                ('encoded_custom_secret_answer', models.CharField(blank=True, db_column='encoded_custom_secret_answer', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('date_joined', models.DateTimeField(db_column='date_joined', default=datetime.datetime.now)),
                ('last_login', models.DateTimeField(db_column='last_login', default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
