
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Kilian', 'Jornet', 'MALE', TO_DATE('1987-10-27', 'YYYY-MM-DD'), 'kilian.jornet@gmail.com', 'Sabadell', 'Spain');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY, PHONE) values ('Mister', 'Sebastien', 'Chaigneau', 'MALE', TO_DATE('1972-02-23', 'YYYY-MM-DD'), 'sebastien.chaigneau@gmail.com', 'Châtellerault', 'France', '+33612345678');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Miss', 'Caroline', 'Chaverot', 'FEMALE', TO_DATE('1976-10-16', 'YYYY-MM-DD'), 'caroline.chaverot@gmail.com', 'Genève', 'Swiss');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Eric', 'Clavery', 'MALE', TO_DATE('1980-06-07', 'YYYY-MM-DD'), 'eric.clavery@gmail.com', 'Coutances', 'France');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'François', 'Delabarre', 'MALE', TO_DATE('1968-01-03', 'YYYY-MM-DD'), 'françois.delabarre@gmail.com', 'Lille', 'France');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY, PHONE) values ('Miss', 'Corinne', 'Favre', 'FEMALE', TO_DATE('1970-12-15', 'YYYY-MM-DD'), 'corinne.favre@gmail.com', 'Chambéry', 'France', '+33 712345678');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Miss', 'Emilie', 'Forsberg', 'FEMALE', TO_DATE('1986-12-11', 'YYYY-MM-DD'), 'emilie.forsberg@gmail.com', 'Sollefteå', 'Sweden');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Miss', 'Anna', 'Frost', 'FEMALE', TO_DATE('1981-11-01', 'YYYY-MM-DD'), 'anna.frost@gmail.com', 'Dunedin', 'New Zealand');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Miss', 'Maud', 'Gobert', 'FEMALE', TO_DATE('1977-04-25', 'YYYY-MM-DD'), 'maud.gobert@gmail.com', '', 'France');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY, PHONE) values ('Mister', 'Antoine', 'Guillon', 'MALE', TO_DATE('1970-06-16', 'YYYY-MM-DD'), 'antoine.guillon@gmail.com', 'Yvelines', 'France', '+33 612345678');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Scott', 'Jurek', 'MALE', TO_DATE('1973-10-26', 'YYYY-MM-DD'), 'scott.jurek@gmail.com', 'Duluth', 'United States');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Anton', 'Krupicka', 'MALE', TO_DATE('1983-08-08', 'YYYY-MM-DD'), 'anton.krupicka@gmail.com', 'Nebraska', 'United States');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Miss', 'Nathalie', 'Mauclair', 'FEMALE', TO_DATE('1970-05-09', 'YYYY-MM-DD'), 'nathalie.mauclair@gmail.com', '', 'France');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY, PHONE) values ('Mister', 'Dawa', 'Dachhiri Sherpa', 'MALE', TO_DATE('1969-11-03', 'YYYY-MM-DD'), 'dawa.dachhiri-sherpa@gmail.com', 'Taksindu Solukumbu', 'Nepal', '+33 712345678');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Xavier', 'Thévenard', 'MALE', TO_DATE('1988-03-06', 'YYYY-MM-DD'), 'xavier.thevenard@gmail.com', 'Nantua', 'France');
insert into trailerplan_schema.user (CIVILITY, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, MAIL, CITY, COUNTRY) values ('Mister', 'Buon', 'Sui', 'MALE', TO_DATE('1974-01-16', 'YYYY-MM-DD'), 'boonsuli@gmail.com', 'Phnom-Penh', 'Cambodia');

update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MAIL', USER_NAME='kilian.jornet@gmail.com', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=1;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MSISDN', USER_NAME='+33612345678', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=2;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NUMBER', USER_NAME='123456', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=3;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NAME', USER_NAME='A12345', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=4;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MAIL', USER_NAME='françois.delabarre@gmail.com', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=5;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MSISDN', USER_NAME='+33712345678', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=6;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NUMBER', USER_NAME='23456789', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=7;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NAME', USER_NAME='R456789', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=8;
update trailerplan_schema.user set USER_CATEGORY='GUEST', ROLE_TYPE='STANDARD', LOGIN_TYPE='MAIL', USER_NAME='maud.gobert@gmail.com', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=9;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MSISDN', USER_NAME='+33623456789', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=10;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NUMBER', USER_NAME='3456789', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=11;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NAME', USER_NAME='DF5678', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=12;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MAIL', USER_NAME='nathalie.mauclair@gmail.com', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=13;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='MSISDN', USER_NAME='+33723456789', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=14;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='USER_NUMBER', USER_NAME='45678', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=15;
update trailerplan_schema.user set USER_CATEGORY='ADMIN', ROLE_TYPE='PRIVILEGED', LOGIN_TYPE='MAIL', USER_NAME='boonsuli@gmail.com', ENCODED_PASSWORD='cGFzc3dvcmQxMjMK', SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==', ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=16;

