
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Kilian', 'Jornet', 'MALE', 'kilian.jornet@gmail.com', 'Spain',  'kilian.jornet@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Sebastien', 'Chaigneau', 'MALE', 'sebastien.chaigneau@gmail.com', 'France', 'sebastien.chaigneau@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Caroline', 'Chaverot', 'FEMALE', 'caroline.chaverot@gmail.com', 'Swiss', 'caroline.chaverot@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Eric', 'Clavery', 'MALE', 'eric.clavery@gmail.com', 'France', 'eric.clavery@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('François', 'Delabarre', 'MALE', 'françois.delabarre@gmail.com', 'France', 'françois.delabarre@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Corinne', 'Favre', 'FEMALE', 'corinne.favre@gmail.com', 'France', 'corinne.favre@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Emilie', 'Forsberg', 'FEMALE', 'emilie.forsberg@gmail.com', 'Sweden', 'emilie.forsberg@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Anna', 'Frost', 'FEMALE', 'anna.frost@gmail.com', 'New Zealand', 'anna.frost@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Maud', 'Gobert', 'FEMALE', 'maud.gobert@gmail.com', 'France', 'maud.gobert@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Antoine', 'Guillon', 'MALE', 'antoine.guillon@gmail.com', 'France', 'antoine.guillon@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Scott', 'Jurek', 'MALE', 'scott.jurek@gmail.com', 'United States', 'scott.jurek@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Anton', 'Krupicka', 'MALE', 'anton.krupicka@gmail.com', 'United States', 'anton.krupicka@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Nathalie', 'Mauclair', 'FEMALE', 'nathalie.mauclair@gmail.com', 'France', 'nathalie.mauclair@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Dawa', 'Dachhiri Sherpa', 'MALE', 'dawa.dachhiri-sherpa@gmail.com', 'Nepal', 'dawa.dachhiri-sherpa@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Xavier', 'Thévenard', 'MALE', 'xavier.thevenard@gmail.com', 'France', 'xavier.thevenard@gmail.com', 'P@55w*rD');
insert into trailerplan_schema.user (FIRST_NAME, LAST_NAME, GENDER,  EMAIL, COUNTRY, USERNAME, PASSWORD) values ('Buon', 'Sui', 'MALE', 'boonsuli@gmail.com', 'Cambodia', 'boonsuli@gmail.com', 'P@55w*rD');

update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=1;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=2;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=3;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=4;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=5;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=6;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=7;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=8;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=9;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=10;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=11;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=12;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=13;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=14;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=15;
update trailerplan_schema.user set USER_CATEGORY='USER', ROLE_TYPE='STANDARD', LOGIN_TYPE='EMAIL' where ID=16;

update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK' where ID=1 ;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=' where ID=2;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==' where ID=3;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==' where ID=4;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK' where ID=5;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=' where ID=6;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==' where ID=7;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==' where ID=8;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK' where ID=9;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=' where ID=10;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==' where ID=11;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==' where ID=12;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='Q2hhbW9uaXgK' where ID=13;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='T3Nsbwo=' where ID=14;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QW1zdGVyZGFtCg==' where ID=15;
update trailerplan_schema.user set SECRET_QUESTION='What is the city of your first job?', ENCODED_SECRET_ANSWER='QmVybGluCg==' where ID=16;

update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=1;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=2;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=3;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=4;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=5;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=6;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=7;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=8;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=9;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=10;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=11;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=12;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=13;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=14;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=15;
update trailerplan_schema.user set ENCODED_CUSTOM_SECRET_QUESTION='V2hhdCBpcyB5b3VyIGZhdm9yaXRlIHNwb3J0Pwo=', ENCODED_CUSTOM_SECRET_ANSWER='VHJhaWwgcnVubmluZwo=' where ID=16;

update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=1;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=2;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=3;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=4;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=5;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=6;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=7;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=8;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=9;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=10;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=11;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=12;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=13;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=14;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=15;
update trailerplan_schema.user set IS_ACTIVE=TRUE, IS_STAFF=TRUE, IS_SUPERUSER=FALSE, DATE_JOINED=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss'), LAST_LOGIN=to_timestamp('20-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=16;

update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=1;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=2;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=3;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=4;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=5;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=6;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=7;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=8;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=9;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=10;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=11;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=12;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=13;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=14;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=15;
update trailerplan_schema.user set CREATED_AT=to_timestamp('01-09-2021 10:00:00', 'dd-mm-yyyy hh24:mi:ss') where ID=16;
